Repository corazawaf/coraza, pull requests merged in 2022-04, with the labels that each got.

#217 fix(actions): Remove branch patterns from action scope
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-ftw.yml
  .github/workflows/lint.yml
  .github/workflows/regression.yml
Labels: gh-actions

#215 fix(@rx): add @rx captured data into Tx variable
  operators/rx.go
  operators/rx_test.go
  seclang/rules_test.go
Labels: bug

#232 feat(directive): Implement include directive
  seclang/parser.go
  seclang/parser_test.go
Labels: enhancement
